### ISSUE TITLE
globalTimelinePostsWithBlock

### ISSUE THREAD

**Issue by YangSugar** [lianleven/LYHTTPClient#1]
globalTimelinePostsWithBlock 这个方法为什么有个俩个 return？ 这个是什么意思啊

**Comment by lianleven** [comment]
下面那个是AFNetworking的Demo例子

**Comment by YangSugar** [comment]
请教您个问题，YYCache做缓存 是不是适用简单的缓存啊。 比如 我取数据， 只想取缓存中前20条数据，能办到吗？

**Comment by lianleven** [comment]
嗯嗯，是的，如果是对数据逻辑处理的较多的话，用数据库或者其他的缓存库，例如：YTKKeyValueStore这个是使用sqllite来做的

**Comment by YangSugar** [comment]
好的。非常谢谢您的回答。
